### ISSUE TITLE
Issue with trying to launch via code editor version

### ISSUE THREAD

**Issue by bkmorimoto** [OfficeDev/Excel-Add-in-JS-QuarterlySalesReport#1]
I setup my windows share and point my manifest to the Home.html file living within the windows share, but still got an error message when trying to load the add-in in excel:
<img width="355" alt="screen shot 2015-12-03 at 4 50 33 pm" src="https://cloud.githubusercontent.com/assets/6611623/11575299/44756d6a-99de-11e5-9cc0-6519999f539a.png">

Basically, it still could not find the file. Ended up having to host of the code online anyways in order to get the add-in to work.

**Comment by umasubra** [comment]
Sorry, it look so long to respond back. Are you still having this or similar issues with this sample?
